"""
parse_high_fidelity_markdown.py
===============================
Expert-level Markdown parser for Sri Lanka Police institutional reports.
Handles parallelized AI outputs with mixed list/header formatting,
extracts incidents, calculates summary matrices, and generates case data.

Usage:
    from parse_high_fidelity_markdown import parse_high_fidelity_markdown
    data = parse_high_fidelity_markdown(markdown_text)
"""

import re
import logging
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("markdown_parser.log", encoding="utf-8", mode="a")
    ]
)
log = logging.getLogger("markdown-parser")


# ── Constants ───────────────────────────────────────────────────────────────
OFFICIAL_PROVINCES = [
    "WESTERN", "SABARAGAMUWA", "SOUTHERN", "UVA", "CENTRAL",
    "NORTH WESTERN", "NORTH CENTRAL", "EASTERN", "NORTHERN"
]

SUMMARY_CATEGORIES = [
    "Theft", "HB & Theft", "Robberies and Armed Robberies", "Rape & Sexual Abuse",
    "Homicide", "Police Accidents", "Fatal Accidents", "Others"
]

# AI filler phrases that indicate empty/invalid sections — skip entirely
AI_FILLER_PHRASES = [
    "no incidents", "no records found", "end of report", "nil", "data summary",
    "source material contained", "no reported incidents", "count verified",
    "no further station", "audit note", "recommendation:", "next steps",
    "processing attempt", "data recovery", "heavily corrupted", "could not be achieved",
    "no verifiable incidents", "summary of processing", "phase 1", "phase 2",
    "phase 3", "phase 4", "not yet been arrested", "zero entries",
    "no data available", "empty section", "placeholder text", "template content",
    "generated by ai", "model output", "inference result", "prediction"
]


# ══════════════════════════════════════════════════════════════════════════════
# UTILITY FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def _ordinal_day(day: int) -> str:
    """Convert day number to ordinal string (1 → '1st', 2 → '2nd', etc.)."""
    if 11 <= day <= 13:
        return f"{day}th"
    return f"{day}{['th', 'st', 'nd', 'rd', 'th', 'th', 'th', 'th', 'th', 'th'][day % 10]}"


def _parse_date_range(text: str) -> Optional[str]:
    """
    Extract and format date range from markdown text.
    Supports multiple formats: DD-MM-YYYY, DD/MM/YYYY, DD.MM.YYYY, etc.
    """
    if not text:
        return None
    
    # Try multiple date patterns
    patterns = [
        r'(\d{1,2})[-/\.](\d{1,2})[-/\.](\d{4})',  # DD-MM-YYYY, DD/MM/YYYY, etc.
        r'(\d{4})[-/\.](\d{1,2})[-/\.](\d{1,2})',  # YYYY-MM-DD
        r'(\d{1,2}[a-z]{2}\s+\w+\s+\d{4})',        # 18th March 2026
    ]
    
    for pattern in patterns:
        match = re.search(pattern, text[:500], re.IGNORECASE)
        if match:
            try:
                groups = match.groups()
                if len(groups) == 3 and groups[0].isdigit():
                    # DD-MM-YYYY or YYYY-MM-DD format
                    if len(groups[2]) == 4:  # Likely DD-MM-YYYY
                        day, month, year = int(groups[0]), int(groups[1]), int(groups[2])
                    else:  # Likely YYYY-MM-DD
                        year, month, day = int(groups[0]), int(groups[1]), int(groups[2])
                    
                    if 1 <= day <= 31 and 1 <= month <= 12:
                        d2 = datetime(year, month, day)
                        d1 = d2 - timedelta(days=1)
                        return f"From 0400 hrs. on {_ordinal_day(d1.day)} of {d1.strftime('%B %Y')} to 0400 hrs. on {_ordinal_day(d2.day)} of {d2.strftime('%B %Y')}"
                elif len(groups) == 1:
                    # Already in ordinal format like "18th March 2026"
                    return f"From 0400 hrs. on {groups[0]} to 0400 hrs. on {_ordinal_day((datetime.strptime(groups[0].split()[0].rstrip('stndrdth'), '%d') + timedelta(days=1)).day)} of {groups[0].split()[1]} {groups[0].split()[2]}"
            except (ValueError, IndexError, AttributeError):
                continue
    
    return None


def _clean_sl_chars(txt: Optional[str]) -> str:
    """
    Strip Sinhala (U+0D80-0DFF) and Tamil (U+0B80-0BFF) script characters,
    but only if the text is predominantly Latin (English).
    Preserves non-Latin text if it's the main content.
    """
    if not txt:
        return ""
    
    txt = txt.strip()
    if not txt:
        return ""
    
    # Count Latin vs non-Latin characters
    latin_chars = len(re.findall(r'[a-zA-Z]', txt))
    total_alpha = len(re.findall(r'\w', txt))
    
    # If text is mostly non-Latin (<30% Latin), return as-is to avoid data destruction
    if total_alpha > 0 and latin_chars / total_alpha < 0.3:
        return txt
    
    # Strip Sinhala and Tamil script characters
    cleaned = re.sub(r'[\u0D80-\u0DFF\u0B80-\u0BFF]+', ' ', txt)
    # Clean up extra spaces
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()
    
    return cleaned


def _normalize_province(name: str) -> str:
    """Normalize province name to official canonical form."""
    if not name:
        return "UNKNOWN"
    
    name = name.strip().upper()
    
    # Handle common variations and abbreviations
    variants = {
        "N. WESTERN": "NORTH WESTERN", "WAYAMBA": "NORTH WESTERN",
        "N. CENTRAL": "NORTH CENTRAL", "RAJARATA": "NORTH CENTRAL",
        "SABARA": "SABARAGAMUWA", "SOUTH": "SOUTHERN",
        "NORTH": "NORTHERN", "EAST": "EASTERN", "WEST": "WESTERN",
        "NORTH-WESTERN": "NORTH WESTERN", "NORTHWESTERN": "NORTH WESTERN",
        "NORTH-CENTRAL": "NORTH CENTRAL", "NORTHCENTRAL": "NORTH CENTRAL",
        "UVA PROVINCE": "UVA", "CENTRAL PROVINCE": "CENTRAL",
    }
    
    normalized = variants.get(name, name)
    
    # Ensure "PROVINCE" suffix for official format
    if "PROVINCE" not in normalized and normalized in OFFICIAL_PROVINCES:
        normalized = f"{normalized} PROVINCE"
    
    return normalized


def _extract_hierarchy(hierarchy_str: str) -> Tuple[str, str, str]:
    """
    Parse hierarchy string into S/DIG, DIG, and Division components.
    Returns: (s_dig, dig, division)
    """
    if not hierarchy_str:
        return "NATIONAL", "", ""
    
    s_dig = "NATIONAL"
    dig = ""
    division = ""
    
    parts = [p.strip() for p in hierarchy_str.split(',') if p.strip()]
    
    for part in parts:
        part_upper = part.upper()
        
        if "S/DIG" in part_upper or "SENIOR DIG" in part_upper:
            s_dig = re.sub(r'S/DIG|SENIOR\s*DIG', '', part, flags=re.IGNORECASE).strip()
            s_dig = re.sub(r'Province', '', s_dig, flags=re.IGNORECASE).strip().upper()
        elif "DIG" in part_upper and "S/DIG" not in part_upper:
            dig = part.strip()
        elif any(x in part_upper for x in ["DIV", "DISTRICT", "DIVISION"]):
            division = part.strip()
    
    return s_dig, dig, division


def _is_ai_filler(text: str) -> bool:
    """Check if text contains AI-generated filler content."""
    if not text:
        return True
    
    text_lower = text.lower()
    
    # Check for filler phrases
    if any(phrase in text_lower for phrase in AI_FILLER_PHRASES):
        return True
    
    # Check for very short content (likely placeholder)
    if len(text.strip()) < 20:
        return True
    
    # Check for "nil" or empty indicators
    if re.search(r'\bnil\b|\bnone\b|\b-\b', text_lower):
        return True
    
    return False


def _extract_reference(text: str) -> str:
    """Extract reference code (CTM/OTM/IR) from text."""
    if not text:
        return ""
    
    # Match patterns like: CTM.370, OTM 1136, IR-123, CTM 370MS
    match = re.search(r'\(?([A-Z]{3,4})[\.\s\-]?(\d+)(MS)?\)?', text, re.IGNORECASE)
    if match:
        prefix, number, suffix = match.groups()
        result = f"{prefix}.{number}"
        if suffix:
            result += suffix
        return result
    
    return ""


def _categorize_incident(body: str, section_title: str) -> int:
    """
    Map incident to summary category index (0-7).
    Returns index into SUMMARY_CATEGORIES list.
    """
    if not body:
        return 7  # Others
    
    body_upper = body.upper()
    title_upper = section_title.upper()
    
    # Explicit keyword matching (order matters - more specific first)
    if "HB & THEFT" in body_upper or "HOUSE BREAK" in body_upper or "BURGLARY" in body_upper:
        return 1  # HB & Theft
    elif "VEHICLE" in body_upper and "THEFT" in body_upper:
        return 0  # Theft (vehicle theft is still theft category for summary)
    elif "THEFT" in body_upper:
        return 0  # Theft
    elif "ROBBER" in body_upper or "SNATCH" in body_upper:
        return 2  # Robberies and Armed Robberies
    elif "RAPE" in body_upper or "SEXUAL ASSAULT" in body_upper or "SEXUAL ABUSE" in body_upper:
        return 3  # Rape & Sexual Abuse
    elif "HOMICIDE" in body_upper or "MURDER" in body_upper or "KILLING" in body_upper:
        return 4  # Homicide
    elif "POLICE" in body_upper and "ACCIDENT" in body_upper:
        return 5  # Police Accidents
    elif "FATAL" in body_upper and "ACCIDENT" in body_upper:
        return 6  # Fatal Accidents
    
    # Fallback to section title hints
    if "THEFT" in title_upper and "HOUSE" not in title_upper:
        return 0
    elif "HOUSE" in title_upper or "BREAK" in title_upper:
        return 1
    elif "ROBBER" in title_upper:
        return 2
    elif "FATAL" in title_upper:
        return 6
    
    return 7  # Others


def _map_to_case_row(body: str) -> int:
    """
    Map incident to official 28-row case table index (0-27).
    Returns index into the 28-row case breakdown.
    """
    if not body:
        return 27  # Others (row 28)
    
    body_upper = body.upper()
    
    # Explicit keyword mapping to 28 official rows
    if any(x in body_upper for x in ["TERROR", "SUBVERSIVE", "EXPLOSIVE ATTACK"]):
        return 0  # Terrorist Activities
    elif any(x in body_upper for x in ["ARMS", "WEAPON", "PISTOL", "GRENADE", "MAOSER", "GUN", "AMMUNITION", "RIFLE"]):
        return 1  # Recovery of Arms & Ammunition
    elif any(x in body_upper for x in ["PROTEST", "STRIKE", "DEMONSTRATION", "UNREST", "RIOT"]):
        return 2  # Protests & Strikes
    elif any(x in body_upper for x in ["HOMICIDE", "MURDER", "KILLING", "FATAL ASSAULT", "DEATH BY STABBING"]):
        return 3  # Homicides
    elif "ROBBER" in body_upper or "ARMED ROBBERY" in body_upper or "SNATCH" in body_upper:
        return 4  # Robberies
    elif "VEHICLE" in body_upper and "THEFT" in body_upper:
        return 5  # Thefts of Vehicles
    elif "THEFT" in body_upper and "HOUSE" not in body_upper and "VEHICLE" not in body_upper:
        return 6  # Thefts of Properties
    elif any(x in body_upper for x in ["HOUSE BREAK", "BURGLARY", "HB &", "BREAKING AND ENTERING"]):
        return 7  # House Breaking & Theft
    elif any(x in body_upper for x in ["RAPE", "SEXUAL ASSAULT", "SEXUAL ABUSE", "CHILD ABUSE", "INDECENT"]):
        return 8  # Rape & Sexual Abuse
    elif "FATAL" in body_upper and "ACCIDENT" in body_upper:
        return 9  # Fatal Accidents
    elif any(x in body_upper for x in ["DEAD BODIES", "SUSPICIOUS DEAD", "FOUND DEAD", "UNIDENTIFIED BODY", "CORPSE"]):
        return 10  # Unidentified dead bodies
    elif "POLICE" in body_upper and "ACCIDENT" in body_upper:
        return 11  # Police Accidents
    elif any(x in body_upper for x in ["NARCOTIC", "HEROIN", "CANNABIS", "GANJA", "ICE", "METH", "COCAINE", "DRUG"]):
        return 18  # Detections of Narcotics
    elif any(x in body_upper for x in ["ILLEGAL LIQUOR", "KASIPPU", "ARRACK", "ILLICIT LIQUOR"]):
        return 18  # Detections of Illicit Liquor
    
    # Default to Others
    return 27


def _is_solved_incident(body: str) -> bool:
    """Check if incident appears to be solved based on keywords."""
    if not body:
        return False
    
    body_lower = body.lower()
    
    solved_keywords = [
        "arrest", "arrested", "apprehend", "apprehended", "remand", "remanded",
        "recover", "recovered", "seized", "confessed", "identified", "charged"
    ]
    
    return any(kw in body_lower for kw in solved_keywords)


# ══════════════════════════════════════════════════════════════════════════════
# MAIN PARSER FUNCTION
# ══════════════════════════════════════════════════════════════════════════════

def parse_high_fidelity_markdown(markdown_text: str) -> Dict[str, Any]:
    """
    Expert-level Markdown parser designed for SL Police reports.
    Handles parallelized AI outputs with mixed list/header formatting.
    
    Args:
        markdown_text: Raw markdown text from AI output
        
    Returns:
        Dictionary with parsed report data:
        {
            "date_range": str,
            "sections": List[Dict],
            "summary_matrix": Dict,
            "case_data": List[Dict]
        }
    """
    if not markdown_text or not isinstance(markdown_text, str):
        log.warning("Empty or invalid markdown text provided")
        return {
            "date_range": "Date information not available",
            "sections": [],
            "summary_matrix": {"headers": SUMMARY_CATEGORIES, "rows": [], "totals": [], "grand_total_all": 0},
            "case_data": []
        }
    
    log.info(f"Parsing markdown: {len(markdown_text)} chars")
    
    data = {
        "date_range": "From 0400 hrs. on 18th March 2026 to 0400 hrs. on 19th March 2026",
        "sections": []
    }
    
    # 1. Date Range extraction
    try:
        parsed_date = _parse_date_range(markdown_text)
        if parsed_date:
            data["date_range"] = parsed_date
    except Exception as e:
        log.warning(f"Date parsing failed: {e}")
    
    # 2. Partition Sections by Header (## 01. ...)
    # Look for headers like "## 01. SERIOUS CRIMES" or similar
    sections_raw = re.split(r'(?:\r?\n|^)##\s*(?=[0-9]{1,2}\.|[IVX]{1,4}\.)', markdown_text)
    
    for sec_chunk in sections_raw:
        if not sec_chunk.strip():
            continue
        
        try:
            # Extract title from the first line
            lines = sec_chunk.strip().split('\n')
            title = lines[0].strip().rstrip(':').strip()
            body = "\n".join(lines[1:]).strip()
            
            if not title:
                continue
            
            section = {"title": title, "provinces": []}
            
            # 3. Flat extract all incidents from section content
            # Search for ### [Station Name] markers
            inc_blocks = re.split(r'(?:\r?\n|^)###\s*', body)
            
            all_section_incidents = []
            
            for block in inc_blocks:
                block = block.strip()
                block_lower = block.lower()
                
                # Skip empty or invalid blocks
                if not block or block.upper().startswith("STATION"):
                    continue
                if _is_ai_filler(block):
                    continue
                
                # Split Title/Station from content
                block_lines = block.split('\n')
                station_raw = block_lines[0].strip().replace("**", "").replace("_", "")
                station = re.sub(r'^\d+[\.\s]*', '', station_raw).strip()
                
                content = "\n".join(block_lines[1:]).strip()
                
                # Extract components using regex patterns
                h_match = re.search(r'(?:\*\*Hierarchy\*\*|Hierarchy)[:\s]+([^\r\n]+)', content, re.IGNORECASE)
                s_match = re.search(r'(?:\*\*Summary\*\*|Summary)[:\s]+([\s\S]+?)(?:\r?\n|$)', content, re.IGNORECASE)
                n_match = re.search(r'(?:\*\*Narrative\*\*|Narrative)[:\s]+([\s\S]+?)(?:\s*\- \*\*Reference\*\*|\s*Reference:|\s*\(?[A-Z]{3}[\.\s]?\d+\)?MS|$)', content, re.IGNORECASE)
                r_match = re.search(r'(\(?[A-Z]{3,4}[\.\s\-]?\d+(MS)?\)?)', content, re.IGNORECASE)
                
                hierarchy_str = _clean_sl_chars(h_match.group(1)) if h_match else ""
                summary = _clean_sl_chars(s_match.group(1)) if s_match else ""
                narrative = _clean_sl_chars(n_match.group(1)) if n_match else content
                ref = _clean_sl_chars(r_match.group(1)) if r_match else _extract_reference(content)
                
                # If no explicit summary but narrative starts with parenthesis, extract it
                if not summary and narrative.strip().startswith('('):
                    paren_match = re.match(r'^\(([^)]+)\)', narrative.strip())
                    if paren_match:
                        summary = paren_match.group(1)
                        narrative = narrative.strip()[len(paren_match.group(0)):].strip()
                
                # Clean summary (ensure it's in parentheses if not already)
                if summary and not summary.startswith('('):
                    summary = f"({summary})"
                
                # Clean narrative - remove metadata labels
                narrative = re.sub(r'(?:\*\*Hierarchy\*\*|Hierarchy)[:\s]+[^\r\n]+', '', narrative, flags=re.IGNORECASE)
                narrative = re.sub(r'(?:\*\*Summary\*\*|Summary)[:\s]+[^\r\n]+', '', narrative, flags=re.IGNORECASE)
                narrative = re.sub(r'(?:\*\*Narrative\*\*|Narrative)[:\s]+', '', narrative, flags=re.IGNORECASE)
                narrative = re.sub(r'[*_]{2,}', '', narrative).strip()
                narrative = narrative.lstrip(':').strip()
                narrative = _clean_sl_chars(narrative)
                
                # Parse Hierarchy
                s_dig, dig, division = _extract_hierarchy(hierarchy_str)
                
                # Skip short or AI-generated filler narratives
                if len(narrative) < 20 or _is_ai_filler(narrative):
                    continue
                
                # Clean Hierarchy: Keep only DIG and Division for incident list
                clean_hierarchy = [p for p in [dig, division] if p]
                
                all_section_incidents.append({
                    "province_target": _normalize_province(s_dig),
                    "station": _clean_sl_chars(station).upper(),
                    "hierarchy": clean_hierarchy,
                    "summary": summary,
                    "body": f"{narrative} {ref}".strip() if ref else narrative,
                    "reference": ref
                })
            
            # 4. Group into Province buckets for the engine
            prov_dict = {}
            for inc in all_section_incidents:
                p_name = inc.pop("province_target")
                if p_name not in prov_dict:
                    prov_dict[p_name] = {"name": p_name, "incidents": []}
                prov_dict[p_name]["incidents"].append(inc)
            
            section["provinces"] = list(prov_dict.values())
            
            if section["provinces"]:
                total_count = sum(len(p["incidents"]) for p in section["provinces"])
                section["count"] = f"{total_count:02d}"
                data["sections"].append(section)
                
        except Exception as e:
            log.warning(f"Failed to parse section chunk: {e}")
            continue
    
    # 5. Statistical Calculations
    try:
        data["summary_matrix"] = calculate_summary_matrix(data)
        data["case_data"] = _calculate_case_data(data["sections"])
    except Exception as e:
        log.error(f"Failed to calculate statistics: {e}")
        data["summary_matrix"] = {"headers": SUMMARY_CATEGORIES, "rows": [], "totals": [], "grand_total_all": 0}
        data["case_data"] = []
    
    log.info(f"Parsing complete: {len(data['sections'])} sections, {sum(len(s['provinces']) for s in data['sections'])} province groups")
    
    return data


# ══════════════════════════════════════════════════════════════════════════════
# STATISTICAL CALCULATION FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def calculate_summary_matrix(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Calculate the 8-category × 9-province summary matrix.
    Used by web_report_engine.py for institutional report generation.
    
    Args:
        data: Parsed report data dictionary
        
    Returns:
        Dictionary with matrix data for report rendering
    """
    sections = data.get("sections", []) if isinstance(data, dict) else data
    
    matrix = {
        "headers": SUMMARY_CATEGORIES,
        "rows": [],
        "totals": [0] * len(SUMMARY_CATEGORIES),
        "grand_total_all": 0
    }
    
    for p_base in OFFICIAL_PROVINCES:
        row = {
            "province": f"{p_base.title()} Province",
            "values": [0] * len(SUMMARY_CATEGORIES),
            "grand_total": 0
        }
        
        for sec in sections:
            s_title = sec["title"].upper()
            for prov in sec["provinces"]:
                # Case-insensitive province matching
                if p_base in prov["name"].upper():
                    for inc in prov["incidents"]:
                        txt = inc.get("body", "").upper()
                        idx = _categorize_incident(inc.get("body", ""), sec["title"])
                        
                        row["values"][idx] += 1
                        row["grand_total"] += 1
                        matrix["totals"][idx] += 1
                        matrix["grand_total_all"] += 1
        
        # Format values: show count if >0, otherwise "-"
        row["values"] = [f"{v:02d}" if v > 0 else "-" for v in row["values"]]
        matrix["rows"].append(row)
    
    # Format totals
    matrix["totals"] = [f"{v:02d}" if v > 0 else "-" for v in matrix["totals"]]
    
    return matrix


def _calculate_case_data(sections: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """
    Calculate the 28-row official case breakdown using incident-level mapping.
    Matches the official Sri Lanka Police summary table format.
    
    Args:
        sections: List of parsed section dictionaries
        
    Returns:
        List of 28 dictionaries with reported/solved/unsolved counts
    """
    # Initialize 28 rows with default values
    rows = [
        {"reported_int": 0, "solved_int": 0, "reported": "-", "solved": "-", "unsolved": "-"}
        for _ in range(28)
    ]
    
    for sec in sections:
        for prov in sec["provinces"]:
            for inc in prov["incidents"]:
                body = inc.get("body", "")
                
                # Map to case row index (0-27)
                idx = _map_to_case_row(body)
                
                # Increment reported count
                rows[idx]["reported_int"] += 1
                
                # Check if incident appears solved
                if _is_solved_incident(body):
                    rows[idx]["solved_int"] += 1
    
    # Format integers to strings for report engine
    for row in rows:
        if row["reported_int"] > 0:
            row["reported"] = f"{row['reported_int']:02d}"
        if row["solved_int"] > 0:
            row["solved"] = f"{row['solved_int']:02d}"
        
        unsolved = row["reported_int"] - row["solved_int"]
        if unsolved > 0:
            row["unsolved"] = f"{unsolved:02d}"
        
        # Remove temporary integer fields
        del row["reported_int"]
        del row["solved_int"]
    
    return rows


# ══════════════════════════════════════════════════════════════════════════════
# TEST & DEMO
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    # Sample markdown for testing
    sample_markdown = """
## 01. SERIOUS CRIMES COMMITTED:

### MADAMPITIYA
**Hierarchy:** S/DIG WESTERN Province, DIG Colombo District, Colombo Div.
**Summary:** (theft of motorcycle)
**Narrative:** A case of theft of a motorcycle bearing #WP BDP 7279 worth Rs. 450,000/= was reported to the police station. The offence took place between 2200 hrs on 12th of March 2026 and 1000 hrs on 13th of March 2026 at Ranmithu Sewana flats, Modara, Colombo 15. Complainant named H. M. K. Akash, (TP 077-8896832). Suspect: Unknown. The stolen motorcycle not recovered and investigations in process. Motive: For illegal gain
**Reference:** CTM.370

### BAMBALAPITIYA
**Hierarchy:** S/DIG WESTERN Province, DIG Colombo District, Colombo Div.
**Summary:** (robbery by snatching)
**Narrative:** A case of robbery of a gold necklace (02 ¼ sovereigns) worth Rs. 800,000/= by snatching was reported to the police station. The offence took place on the 12th of March 2026 between 1700 hrs and 1710 hrs at #10, Kristen Place, Bambalapitiya, Colombo 04. Complainant named M. K. P. C. Perera, (TP 077-7864921) Suspect: Unknown. The robbed necklace not recovered and investigations in process. Motive: For illegal gain.
**Reference:** CTM.393
"""
    
    print("🧪 Markdown Parser — Quick Test")
    print("=" * 70)
    
    result = parse_high_fidelity_markdown(sample_markdown)
    
    print(f"📅 Date Range: {result['date_range']}")
    print(f"📊 Sections: {len(result['sections'])}")
    
    for sec in result['sections']:
        print(f"\n  {sec['title']} ({sec.get('count', '00')} incidents)")
        for prov in sec['provinces']:
            print(f"    - {prov['name']}: {len(prov['incidents'])} incidents")
            for inc in prov['incidents'][:2]:  # Show first 2 incidents
                print(f"      • {inc['station']}: {inc['summary']} {inc.get('reference', '')}")
    
    print(f"\n📈 Summary Matrix: {result['summary_matrix']['grand_total_all']} total incidents")
    print(f"📋 Case Data: {len(result['case_data'])} rows")
    
    print("\n✅ Test complete.")